# Generated by Django 2.2.1 on 2019-05-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('algorithm', models.CharField(max_length=50)),
                ('proofType', models.CharField(max_length=25)),
                ('totalCoinSupply', models.DecimalField(decimal_places=2, max_digits=32)),
                ('isTrading', models.BooleanField(default=False)),
                ('totalCoinsMined', models.DecimalField(decimal_places=2, max_digits=32)),
                ('blockNumber', models.IntegerField()),
                ('netHashesPerSecond', models.DecimalField(decimal_places=2, max_digits=32)),
                ('blockReward', models.DecimalField(decimal_places=2, max_digits=10)),
                ('blockTime', models.IntegerField(default=-1)),
            ],
        ),
    ]
