# Generated by Django 2.2.1 on 2019-05-13 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='blockReward',
            field=models.DecimalField(decimal_places=16, max_digits=32),
        ),
        migrations.AlterField(
            model_name='coin',
            name='netHashesPerSecond',
            field=models.DecimalField(decimal_places=8, max_digits=40),
        ),
        migrations.AlterField(
            model_name='coin',
            name='symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='totalCoinsMined',
            field=models.DecimalField(decimal_places=8, max_digits=40),
        ),
    ]
