# Generated by Django 2.2.1 on 2019-05-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_auto_20190513_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='blockNumber',
            field=models.IntegerField(default=-1),
        ),
    ]
