# Generated by Django 2.2.1 on 2019-05-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_auto_20190513_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='proofType',
            field=models.CharField(max_length=50),
        ),
    ]
