# Generated by Django 2.1.7 on 2019-03-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(max_length=10)),
                ('imageurl', models.TextField()),
                ('source', models.CharField(max_length=50)),
                ('url', models.TextField()),
                ('title', models.TextField()),
                ('categories', models.TextField()),
            ],
        ),
    ]
