# Generated by Django 2.1.7 on 2019-03-06 04:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190302_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='when_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
